name: Soccer Python Application

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '2 *23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository Content
        uses: actions/checkout@v3 # Checkout the repository content to GitHub runner.

      - name: Setup Python Version
        uses: actions/setup-python@v3
        with:
          python-version: 3.11 # Install the Python version needed

      - name: Install Python Dependencies
        run: python -m pip install --upgrade pip pandas plotly streamlit 

      - name: Execute Data Processing Pipeline
        run: |
          python -m data_processing.fetch_data
          python -m data_processing.process_statistics
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "APPENDED NEW DATA TO ----team_statistics.csv---- file"
          git pull --rebase
          git push

#      - name: Run Unit Tests
 #       run: pytest --junitxml=test-results.xml --tb=short
#
 #     - name: Upload Test Results
  #      uses: actions/upload-artifact@v3
   #     with:
    #      name: test-results
     #     path: test-results.xml

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
